### ISSUE TITLE
Nil pointer dereference

### ISSUE THREAD

**Issue by quasilyte** [go-toolsmith/pkgload#6]
```
2019/01/11 18:45:28 ERROR: exit status 2: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x757aba]

goroutine 1 [running]:
github.com/go-toolsmith/pkgload.VisitUnits.func4(0x4, 0x0, 0x1)
	$GOPATH/src/github.com/go-toolsmith/pkgload/pkgload.go:125 +0x3a
sort.doPivot_func(0xc4206f18e0, 0xc42113d7c0, 0x0, 0x14, 0x18, 0xc42113d460)
	$GOROOT/src/sort/zfuncversion.go:83 +0xda
sort.quickSort_func(0xc4206f18e0, 0xc42113d7c0, 0x0, 0x14, 0xa)
	$GOROOT/src/sort/zfuncversion.go:143 +0x8a
sort.Slice(0x7c92c0, 0xc42113d460, 0xc4206f18e0)
	$GOROOT/src/sort/slice.go:21 +0xe3
github.com/go-toolsmith/pkgload.VisitUnits(0xc425566640, 0x25, 0x25, 0xc4206f1ab8)
	$GOPATH/src/github.com/go-toolsmith/pkgload/pkgload.go:124 +0x940
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.loadPackages(0xc42006bbc8, 0xc4200019a0, 0x14, 0x16, 0xc4200987e8, 0x83fe01, 0x1, 0x84291e, 0xd)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:441 +0xee
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.(*linter).loadProgram(0xc42013e000, 0x0, 0x0)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:249 +0x111
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.(*linter).(github.com/go-lintpack/lintpack/linter/lintmain/internal/check.loadProgram)-fm(0x0, 0x0)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:41 +0x2a
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.Main()
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:48 +0x356
github.com/go-lintpack/lintpack/internal/cmdutil.DispatchCommand(0xc42006bf30, 0x3, 0x3)
	$GOPATH/src/github.com/go-lintpack/lintpack/internal/cmdutil/cmdutil.go:49 +0x17f
github.com/go-lintpack/lintpack/linter/lintmain.Run(0x84041e, 0x5, 0x84087d, 0x6)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/lintmain.go:63 +0x4af
main.main()
	/tmp/linter787676832.go:11 +0x4b
```

**Comment by cristaloleg** [comment]
Any specific package?
